#error: error validating "hog.yml": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].resources): unknown field "args" in io.k8s.api.core.v1.ResourceRequirements; if you choose to ignore these errors, turn validation off with --validate=false
#hog.yml also worked as the args needs to be aligned to resources and not to requests
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: hog
  name: hog
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/hog
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hog
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hog
    spec:
      containers:
      - image: vish/stress
        imagePullPolicy: Always
        name: stress
        resources: 
          limits: 
            memory: "4Gi"
          requests:
                  memory: "2500Mi"
        args: ["-cpus","2","-mem-total","950Mi","-mem-alloc-size","100Mi","-mem-alloc-sleep","1s"]
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
